In [1]:
import pandas as pd
import numpy as np

In [2]:
# ładowanie danych
portfolio = pd.read_csv('przykladowe_portfolio.txt', sep=';')
wskazniki = pd.read_csv('przykladowe_wskazniki.txt', sep=';')
# usuwam jedną niepotrzebną kolumnę która mi się zrobiła przypadkowo przy tworzeniu przykładowych danych
wskazniki.drop('Unnamed: 2', inplace=True, axis=1)

In [3]:
portfolio

nazwa  liczba_akcji  obecny_kurs
0               Adobe             2         35.0
1              Makita             3         17.0
2   21 st Century Fox             4         23.0
3           Starbucks             5         12.0
4            Facebook             7         30.0
5          BlackBerry             2         55.0
6                EBay            12         11.0
7             Netflix            15          9.0
8             Moderna             3         34.0
9         AstraZeneca             5         14.0
10              Apple             4         46.0
11             NASDAQ             1        130.0
12             Garmin            29          6.0

In [4]:
# liczę wartość posiadanych akcji każdej firmy
portfolio['wartosc'] = portfolio['liczba_akcji'] * portfolio['obecny_kurs']
# zsumowana wartość całego portfolio przy obecnym kursie 
portfolio_value = portfolio['wartosc'].sum()
print('portfolio_value', portfolio_value)
# procent wartości akcji w stosunku do wartości całego portfolio
portfolio['procent_wartosci'] = portfolio['wartosc'] / portfolio_value

portfolio_value 1520.0


In [5]:
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci
0               Adobe             2         35.0     70.0          0.046053
1              Makita             3         17.0     51.0          0.033553
2   21 st Century Fox             4         23.0     92.0          0.060526
3           Starbucks             5         12.0     60.0          0.039474
4            Facebook             7         30.0    210.0          0.138158
5          BlackBerry             2         55.0    110.0          0.072368
6                EBay            12         11.0    132.0          0.086842
7             Netflix            15          9.0    135.0          0.088816
8             Moderna             3         34.0    102.0          0.067105
9         AstraZeneca             5         14.0     70.0          0.046053
10              Apple             4         46.0    184.0          0.121053
11             NASDAQ             1        130.0    130.0          0.085526
12             Garmin            29          6.0    174.0          0.114474

In [6]:
wskazniki

sredni_zysk  srednie_odchylenie
0         0.534               5.465
1        -1.749               6.544
2         1.837               7.734
3         0.352               6.283
4         0.163               8.365
5         0.857               4.869
6        -0.874               2.134
7        -0.632               6.674
8         1.375               5.872
9         0.386               3.985
10       -1.474               7.862
11        0.284               4.236
12        1.347               8.357

In [7]:
# łączenie tabeli portfolio z tabelą wskaźniki
portfolio = portfolio.join(wskazniki)
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  
0         0.534               5.465  
1        -1.749               6.544  
2         1.837               7.734  
3         0.352               6.283  
4         0.163               8.365  
5         0.857               4.869  
6        -0.874               2.134  
7        -0.632               6.674  
8         1.375               5.872  
9         0.386               3.985  
10       -1.474               7.862  
11        0.284               4.236  
12        1.347               8.357

In [8]:
# licze sharpe ratio
portfolio['sharpe_ratio'] = portfolio['sredni_zysk'] / portfolio['srednie_odchylenie']
portfolio
# średni zysk = expected return w filmiku
# średnie odchylenie = standard deviation w filmiku
# sharpe ratio to tak samo

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  sharpe_ratio  
0         0.534               5.465      0.097713  
1        -1.749               6.544     -0.267268  
2         1.837               7.734      0.237523  
3         0.352               6.283      0.056024  
4         0.163               8.365      0.019486  
5         0.857               4.869      0.176012  
6        -0.874               2.134     -0.409560  
7        -0.632               6.674     -0.094696  
8         1.375               5.872      0.234162  
9         0.386               3.985      0.096863  
10       -1.474               7.862     -0.187484  
11        0.284               4.236      0.067044  
12        1.347               8.357      0.161182

In [9]:
# losuję przykładową macierz waiancji-kowariancji
covariance_matrix = 0.008 * np.random.rand(13,13) - 0.003
covariance_matrix

array([[ 2.84871618e-03, -2.67321262e-03,  2.28413324e-03,
         4.19049390e-03,  1.64494118e-03,  7.48550140e-04,
        -2.66331659e-03,  8.72162439e-04,  4.79167077e-03,
         4.70925740e-03,  4.27018617e-03,  9.40862035e-05,
         2.05608827e-03],
       [ 2.52874996e-03,  1.00104419e-03,  2.26216928e-04,
         3.75052048e-03,  2.69275466e-03, -2.68491207e-03,
        -2.14945730e-03, -1.04097076e-03,  3.80860222e-03,
        -5.72703676e-04,  2.33868616e-03, -2.43802112e-04,
         2.80907407e-03],
       [ 4.75575995e-03,  3.86215173e-03,  4.36569754e-03,
         4.88736291e-03,  1.63311939e-03, -6.08658109e-04,
         8.10831191e-04,  1.02421407e-03, -2.63211451e-03,
        -2.58814518e-03,  4.06310937e-03,  4.71898758e-04,
         5.80658116e-04],
       [ 2.28893573e-03,  3.00660581e-03,  1.32689994e-04,
         3.35524865e-03,  4.06135731e-03,  6.27576853e-04,
        -1.97599778e-03,  3.16813322e-03, -2.39852852e-03,
        -1.82573868e-03, -5.48816999e

In [10]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = (portfolio['sredni_zysk'] * portfolio['procent_wartosci']).sum()
portfolio_exp_return

0.15359802631578942

In [11]:
# zamieniam pandasową kolumnę na format akceptowany przez numpy
weights = portfolio['procent_wartosci'].to_numpy()

In [12]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.0308919023848217

In [13]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

4.972112898791809

# Test dla danych (prawie takich samych) jak w filmiku na yt

In [14]:
portfolio = pd.read_csv('film_portfolio.txt')
portfolio

name  exp_ret  std_dev  weights
0  SPY -0.00033  0.05465    0.125
1  MDY  0.00235  0.06544    0.125
2  SLY  0.00228  0.07204    0.125
3  EFA -0.00439  0.06946    0.125
4  EEM  0.00124  0.08707    0.125
5  TLT  0.00818  0.04594    0.125
6  LQD  0.00539  0.02858    0.125
7  GLD  0.01462  0.06016    0.125

In [15]:
# licze sharpe ratio
# to jest tabelka dokładnie taka jak w filmie
portfolio['sharpe_ratio'] = portfolio['exp_ret'] / portfolio['std_dev']
portfolio

name  exp_ret  std_dev  weights  sharpe_ratio
0  SPY -0.00033  0.05465    0.125     -0.006038
1  MDY  0.00235  0.06544    0.125      0.035911
2  SLY  0.00228  0.07204    0.125      0.031649
3  EFA -0.00439  0.06946    0.125     -0.063202
4  EEM  0.00124  0.08707    0.125      0.014241
5  TLT  0.00818  0.04594    0.125      0.178058
6  LQD  0.00539  0.02858    0.125      0.188593
7  GLD  0.01462  0.06016    0.125      0.243019

In [16]:
# 3 wartości których potrzebuję potem w solverze
maximum_expected_return = max(portfolio['exp_ret'])
maximum_expected_return

0.01462

In [17]:
minimum_standard_deviation = min(portfolio['std_dev'])
minimum_standard_deviation

0.02858

In [18]:
maximum_sharpe_ratio = max(portfolio['sharpe_ratio'])
maximum_sharpe_ratio

0.24301861702127658

In [19]:
# macierz kowariancji taka jak w filmiku
# tak, przepisywałam to wszystko XD
covariance_matrix = pd.read_csv('film_kowariancja.txt', names=['SPY','MDY','SLY','EFA','EEM','TLT','LQD','GLD'])
covariance_matrix

SPY       MDY       SLY       EFA       EEM       TLT       LQD  \
0  0.002987  0.003433  0.003759  0.003552  0.004195 -0.000690  0.000566   
1  0.003433  0.004282  0.004645  0.004051  0.005018 -0.000980  0.000624   
2  0.003759  0.004645  0.005190  0.004387  0.005371 -0.001040  0.000662   
3  0.003552  0.004051  0.004387  0.004824  0.005585 -0.000570  0.000899   
4  0.004195  0.005018  0.005371  0.005585  0.007582 -0.001080  0.000921   
5 -0.000690 -0.000980 -0.001040 -0.000570 -0.001080  0.002111  0.000516   
6  0.000566  0.000624  0.000662  0.000899  0.000921  0.000516  0.000817   
7  0.000345  0.000498  0.000352  0.000767  0.001528  0.000425  0.000291   

        GLD  
0  0.000345  
1  0.000498  
2  0.000352  
3  0.000767  
4  0.001528  
5  0.000425  
6  0.000291  
7  0.003619

In [20]:
# zmieniam se tylko format tej tabelki na brzydszy nampajowy
covariance_matrix = covariance_matrix.to_numpy()
covariance_matrix

array([[ 0.002987,  0.003433,  0.003759,  0.003552,  0.004195, -0.00069 ,
         0.000566,  0.000345],
       [ 0.003433,  0.004282,  0.004645,  0.004051,  0.005018, -0.00098 ,
         0.000624,  0.000498],
       [ 0.003759,  0.004645,  0.00519 ,  0.004387,  0.005371, -0.00104 ,
         0.000662,  0.000352],
       [ 0.003552,  0.004051,  0.004387,  0.004824,  0.005585, -0.00057 ,
         0.000899,  0.000767],
       [ 0.004195,  0.005018,  0.005371,  0.005585,  0.007582, -0.00108 ,
         0.000921,  0.001528],
       [-0.00069 , -0.00098 , -0.00104 , -0.00057 , -0.00108 ,  0.002111,
         0.000516,  0.000425],
       [ 0.000566,  0.000624,  0.000662,  0.000899,  0.000921,  0.000516,
         0.000817,  0.000291],
       [ 0.000345,  0.000498,  0.000352,  0.000767,  0.001528,  0.000425,
         0.000291,  0.003619]])

In [21]:
# kolumnę weights też potrzebuję w formacie numpy żeby policzyć reszte rzeczy
weights = portfolio['weights'].to_numpy()
weights

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

#### w tych 3 komórkach poniżej sprawdzam tylko czy dobrze liczę, odpowiednie funkcje do liczenia tych rzeczy są niżej

In [22]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = np.matmul(portfolio['exp_ret'], portfolio['weights'])
portfolio_exp_return

0.0036674999999999998

In [23]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.04462902642899574

In [24]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

0.08217745923350915

### okej, wszystko do tego momentu śmiga jak trzeba

In [25]:
import scipy.optimize as opt

In [26]:
# funkcja która liczy na raz odchylenie standardowe portfolio w zależności od wag
# covariance_matrix musi być zmienną globalną
def get_portfolio_std_deviation(weights):
    portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
    return portfolio_std_deviation

In [27]:
get_portfolio_std_deviation(weights)

0.04462902642899574

In [28]:
exp_returns = portfolio['exp_ret'].to_numpy()

In [29]:
# funkcja która liczy na raz oczekiwany zwrot z portfolio w zależności od wag
# exp_returns musi być zmienną globalną
def get_portfolio_exp_return(weights):
    portfolio_exp_return = np.matmul(exp_returns, weights)
    return portfolio_exp_return

In [30]:
get_portfolio_exp_return(weights)

0.0036674999999999998

In [31]:
# funkcja która liczy na raz sharpe ratio całego portfolio w zależności od wag
# covariance_matrix musi być zmienną globalną
def get_portfolio_sharpe_ratio(weights):
    portfolio_sharpe_ratio = np.matmul(exp_returns, weights) / np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
    return portfolio_sharpe_ratio

In [32]:
get_portfolio_sharpe_ratio(weights)

0.08217745923350915

### Optymalizacja z 2 kolumny (nazwanej w filmiku Max Ret):
##### maksymalizuję expected return przy utrzymaniu najniższego standard deviation jakie było w portfolio

In [33]:
# ograniczenie, że liczba akcji
# (dokładniej wagi czyli stosunek wartości akcji względem wartości całego portfolio) 
# nie może być ujemna
# to ograniczenie stosuję we wszystkich 3 typach optymalizacji
bnds = ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None))

In [34]:
# ograniczenie, że wszytskie wagi razem wzięte muszą wynosić 1 (100%)
# ograniczenie że portfolio std deviation ma pozostać nie większe, niż było w portfolio
# get_portfolio_std_deviation <= minimum_standard_deviation
# minimum_standard_deviation - get_portfolio_std_deviation >= 0

cons = ({'type': 'eq', 'fun': lambda x:  sum(x) - 1},
        {'type': 'ineq', 'fun': lambda x: minimum_standard_deviation - get_portfolio_std_deviation(x)})

In [37]:
def get_portfolio_exp_return_reversed(weights):
    return 1/get_portfolio_exp_return(weights)

In [38]:
result = opt.minimize(get_portfolio_exp_return_reversed, weights, bounds=bnds, constraints=cons)
result

     fun: 117.74154788370274
     jac: array([   4.5748148 ,  -32.57821846,  -31.6078043 ,   60.85888672,
        -17.19020939, -113.39992809,  -74.72195721, -202.67810917])
 message: 'Optimization terminated successfully'
    nfev: 121
     nit: 13
    njev: 13
  status: 0
 success: True
       x: array([0.00000000e+00, 3.89876240e-12, 4.14806224e-02, 0.00000000e+00,
       1.02541627e-12, 2.30937385e-01, 4.47206253e-01, 2.80375739e-01])

### Optymalizacja z 3 kolumny (nazwanej w filmiku Min St Dev):
##### minimalizuję std deviation przy utrzymaniu największego expected return jakie było w portfolio

In [39]:
# ograniczenie, że wszytskie wagi razem wzięte muszą wynosić 1 (100%)
# ograniczenie że portfolio expected return ma pozostać nie mniejsze, niż było w portfolio
# get_portfolio_exp_return >= maximum_expected_return
# get_portfolio_exp_return - maximum_expected_return >= 0

cons = ({'type': 'eq', 'fun': lambda x:  sum(x) - 1},
        {'type': 'ineq', 'fun': lambda x: get_portfolio_exp_return(x) - maximum_expected_return})

In [40]:
# tutaj działa solver i z ważnych rzeczy wypluwa:
# fun: to jest najlepszy wynik funkcji jaki się udało uzyskać, w tym przypadku minimalne std deviation
# x: to są wagi dające minimalne std deviation, to jest najważniejsza rzecz u nas
#    (mówi co użytkownik ma pozmieniać, żeby uzyskać najlepsze wyniki)
result = opt.minimize(get_portfolio_std_deviation, weights, constraints=cons)
result

     fun: 0.031603538067684
     jac: array([-0.00033831,  0.0054703 ,  0.00524215, -0.0090188 ,  0.00309087,
        0.0178373 ,  0.01183114,  0.03154177])
 message: 'Optimization terminated successfully'
    nfev: 270
     nit: 30
    njev: 30
  status: 0
 success: True
       x: array([ 0.41892488,  0.25630422,  0.14996736, -1.12117764,  0.24361841,
        0.22786211,  0.57726582,  0.24723483])

In [41]:
# tak się uzyskuje same wagi, żeby potem je gdzieś przekazać czy wyświetlić
result.x

array([ 0.41892488,  0.25630422,  0.14996736, -1.12117764,  0.24361841,
        0.22786211,  0.57726582,  0.24723483])

In [42]:
# a tak wynik
result.fun

0.031603538067684

In [43]:
# można se też sprawdzić czy wagi fajnie sumują się do 1 (100%)
sum(result.x)

1.0

### Optymalizacja z 4 kolumny (nazwanej w filmiku Max SR):
##### maksymalizuję sharpe ratio przy utrzymaniu największego expected return i najmniejszego std deviation jakie było w portfolio

In [44]:
# tutaj zgodnie z filmikiem bez dodatkowych ograniczeń (hulaj dusza boga nie ma :)
# ograniczenie jest tylko to, że wszytskie wagi razem wzięte muszą wynosić 1 (100%)

cons = ({'type': 'eq', 'fun': lambda x:  sum(x) - 1})

In [45]:
def get_sharpe_ratio_reversed(weights):
    return 1/get_portfolio_sharpe_ratio(weights)

In [46]:
result = opt.minimize(get_sharpe_ratio_reversed, weights, bounds=bnds, constraints=cons)
result

     fun: 3.329326675467473
     jac: array([ 9.91588593e-01,  1.14394963e-01, -3.59117985e-04,  3.56373417e+00,
        2.15000427e+00,  3.30209732e-04, -2.67922878e-05, -1.77800655e-04])
 message: 'Optimization terminated successfully'
    nfev: 93
     nit: 10
    njev: 10
  status: 0
 success: True
       x: array([1.19366892e-16, 2.27789815e-16, 2.18182133e-02, 0.00000000e+00,
       1.07970842e-16, 2.44990449e-01, 3.79507820e-01, 3.53683518e-01])